spring.application.name=course-management
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.jwt.secret=${JWT_SECRET:mySecretKeyForCourseManagementSystem2024MustBeLongEnough256Bits!!}
app.jwt.expiration-ms=86400000

app.upload.dir=uploads

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
